### ISSUE TITLE
estimators tutorial

### ISSUE THREAD

**Issue by bpablo** [phoebe-project/phoebe2-workshop#2]
- [ ] scikit-learn neede for ebai knn. Should let users know ahead of time or make it a phoebe dependency?
- [ ] issue running in line 17.  b.run_solver('ebai_knn_est', solution='ebai_knn_solution') results in the following error:

      2 import warnings
      3 import matplotlib.pyplot as plt
----> 4 plt.style.use('science')
      5 from scipy.interpolate import interp1d

OSError: 'science' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles.

I recognize this is just a missing style file, but we really need to include them, if they are necessary for running certain routines. Unsure who to tag for this so I'm just tagging everyone.

**Comment by gecheline** [comment]
You can remove the styling issues as you go through the tutorials (I did for some of Andrej's I think). As for scikit-learn the error should be informative enough for the general public as it's a soft dependency needed only for that particular estimator. As far as the workshop goes, we can let the participants know in advance to have it installed (alongside emcee, corner and all of the other soft dependencies needed for fitting)

**Comment by bpablo** [comment]
This styling issue isn't in the tutorial though, it's part of the run_solver command for that particular estimator. I don't think I can disable it, unless you mean to go into the code itself and remove it and and re-build phoebe.

**Comment by gecheline** [comment]
oh I tracked that line down to ligeor and it has no business being there, thanks for catching it! I pushed a fix without it to the Phoebe_2.4dev branch
